<a href="https://colab.research.google.com/github/9terry-student/pytorch/blob/main/01_Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch

#tensor는 numpy와 비슷한 개념
x=torch.tensor([1.0,2.0,3.0])
print(x)
print(x.shape)

y=torch.tensor([4.0,5.0,6.0])
z=x+y
print(z)

z=x*y
print(z)

#미적분에도 활용 가능
x=torch.tensor([2.0],requires_grad=True)
y=x**2+3*x+1
y.backward()
print(x.grad)

#그래프라는 개념으로도 볼 수 있음
x=torch.tensor([1.0],requires_grad=True)
y=x*2
z=y**2
z.backward()
print(x.grad)

import torch.nn as nn

class SimpleModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)

model=SimpleModel()
print(model)

for name, param in model.named_parameters():
  print(name,param.data)

x=torch.randn(100,1)
y=3*x+2

criterion=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)

for epoch in range(20):
  optimizer.zero_grad()
  y_hat=model(x)
  loss=criterion(y_hat,y)
  loss.backward()
  optimizer.step()

  print(f"Epoch {epoch:02d} | Loss: {loss.item():.4f}")

for name, param in model.named_parameters():
  print(name,param.data)

tensor([1., 2., 3.])
torch.Size([3])
tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([7.])
tensor([8.])
SimpleModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
linear.weight tensor([[0.7196]])
linear.bias tensor([-0.1036])
Epoch 00 | Loss: 8.1734
Epoch 01 | Loss: 5.6034
Epoch 02 | Loss: 3.8516
Epoch 03 | Loss: 2.6541
Epoch 04 | Loss: 1.8333
Epoch 05 | Loss: 1.2692
Epoch 06 | Loss: 0.8806
Epoch 07 | Loss: 0.6122
Epoch 08 | Loss: 0.4264
Epoch 09 | Loss: 0.2976
Epoch 10 | Loss: 0.2080
Epoch 11 | Loss: 0.1456
Epoch 12 | Loss: 0.1021
Epoch 13 | Loss: 0.0717
Epoch 14 | Loss: 0.0504
Epoch 15 | Loss: 0.0354
Epoch 16 | Loss: 0.0250
Epoch 17 | Loss: 0.0176
Epoch 18 | Loss: 0.0124
Epoch 19 | Loss: 0.0088
linear.weight tensor([[2.9180]])
linear.bias tensor([1.9669])
